<?php
return array (
  0 => 
  array (
    'prenom' => 'Pierre',
    'nom' => 'Durand',
    'mail' => 'pierre.durand@univ.fr',
    'tel' => 611223344,
    'adresse' => '12 Rue de la Fac',
    'genre' => 'Homme',
    'date_naissance' => '1980-05-12',
    'login' => 'pdurand',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  1 => 
  array (
    'prenom' => 'Sophie',
    'nom' => 'Martin',
    'mail' => 'sophie.martin@univ.fr',
    'tel' => 699887766,
    'adresse' => '45 Avenue des Sciences',
    'genre' => 'Femme',
    'date_naissance' => '1975-09-23',
    'login' => 'smartin',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  2 => 
  array (
    'prenom' => 'Marc',
    'nom' => 'Lefebvre',
    'mail' => 'marc.lefebvre@univ.fr',
    'tel' => 655443322,
    'adresse' => '8 Impasse du Code',
    'genre' => 'Homme',
    'date_naissance' => '1982-11-04',
    'login' => 'mlefebvre',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  3 => 
  array (
    'prenom' => 'Isabelle',
    'nom' => 'Dubois',
    'mail' => 'isabelle.dubois@univ.fr',
    'tel' => 622334455,
    'adresse' => '3 Boulevard Java',
    'genre' => 'Femme',
    'date_naissance' => '1979-03-30',
    'login' => 'idubois',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  4 => 
  array (
    'prenom' => 'Jean',
    'nom' => 'Moreau',
    'mail' => 'jean.moreau@univ.fr',
    'tel' => 612345678,
    'adresse' => '10 Rue Linux',
    'genre' => 'Homme',
    'date_naissance' => '1985-07-14',
    'login' => 'jmoreau',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  5 => 
  array (
    'prenom' => 'Claire',
    'nom' => 'Leroy',
    'mail' => 'claire.leroy@univ.fr',
    'tel' => 687654321,
    'adresse' => '22 Allée Python',
    'genre' => 'Femme',
    'date_naissance' => '1990-02-18',
    'login' => 'cleroy',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  6 => 
  array (
    'prenom' => 'Thomas',
    'nom' => 'Roux',
    'mail' => 'thomas.roux@univ.fr',
    'tel' => 601020304,
    'adresse' => '5 Place SQL',
    'genre' => 'Homme',
    'date_naissance' => '1988-12-05',
    'login' => 'troux',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  7 => 
  array (
    'prenom' => 'Julie',
    'nom' => 'Petit',
    'mail' => 'julie.petit@univ.fr',
    'tel' => 690807060,
    'adresse' => '78 Rue du Web',
    'genre' => 'Femme',
    'date_naissance' => '1992-06-25',
    'login' => 'jpetit',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  8 => 
  array (
    'prenom' => 'Nicolas',
    'nom' => 'Blanc',
    'mail' => 'nicolas.blanc@univ.fr',
    'tel' => 611111111,
    'adresse' => '30 Avenue Réseau',
    'genre' => 'Homme',
    'date_naissance' => '1983-08-30',
    'login' => 'nblanc',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  9 => 
  array (
    'prenom' => 'Sarah',
    'nom' => 'Garnier',
    'mail' => 'sarah.garnier@univ.fr',
    'tel' => 622222222,
    'adresse' => '14 Boulevard IOT',
    'genre' => 'Femme',
    'date_naissance' => '1995-04-12',
    'login' => 'sgarnier',
    'motdepasse' => 'hash_prof',
    'statut' => 'ENSEIGNANT',
  ),
  10 => 
  array (
    'prenom' => 'Lucas',
    'nom' => 'Bernard',
    'mail' => 'lucas.bernard@etu.univ.fr',
    'tel' => 645123456,
    'adresse' => '1 Rue A',
    'genre' => 'Homme',
    'date_naissance' => '2005-01-15',
    'login' => 'lbernard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  11 => 
  array (
    'prenom' => 'Emma',
    'nom' => 'Thomas',
    'mail' => 'emma.thomas@etu.univ.fr',
    'tel' => 645123457,
    'adresse' => '2 Rue B',
    'genre' => 'Femme',
    'date_naissance' => '2005-02-20',
    'login' => 'ethomas',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  12 => 
  array (
    'prenom' => 'Hugo',
    'nom' => 'Robert',
    'mail' => 'hugo.robert@etu.univ.fr',
    'tel' => 645123458,
    'adresse' => '3 Rue C',
    'genre' => 'Homme',
    'date_naissance' => '2005-03-10',
    'login' => 'hrobert',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  13 => 
  array (
    'prenom' => 'Jade',
    'nom' => 'Richard',
    'mail' => 'jade.richard@etu.univ.fr',
    'tel' => 645123459,
    'adresse' => '4 Rue D',
    'genre' => 'Femme',
    'date_naissance' => '2005-04-05',
    'login' => 'jrichard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  14 => 
  array (
    'prenom' => 'Leo',
    'nom' => 'Petit',
    'mail' => 'leo.petit@etu.univ.fr',
    'tel' => 645123460,
    'adresse' => '5 Rue E',
    'genre' => 'Homme',
    'date_naissance' => '2005-05-25',
    'login' => 'lpetit',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  15 => 
  array (
    'prenom' => 'Chloe',
    'nom' => 'Durand',
    'mail' => 'chloe.durand@etu.univ.fr',
    'tel' => 645123461,
    'adresse' => '6 Rue F',
    'genre' => 'Femme',
    'date_naissance' => '2005-06-30',
    'login' => 'cdurand',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  16 => 
  array (
    'prenom' => 'Louis',
    'nom' => 'Leroy',
    'mail' => 'louis.leroy@etu.univ.fr',
    'tel' => 645123462,
    'adresse' => '7 Rue G',
    'genre' => 'Homme',
    'date_naissance' => '2005-07-15',
    'login' => 'lleroy',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  17 => 
  array (
    'prenom' => 'Mia',
    'nom' => 'Moreau',
    'mail' => 'mia.moreau@etu.univ.fr',
    'tel' => 645123463,
    'adresse' => '8 Rue H',
    'genre' => 'Femme',
    'date_naissance' => '2005-08-10',
    'login' => 'mmoreau',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  18 => 
  array (
    'prenom' => 'Gabriel',
    'nom' => 'Simon',
    'mail' => 'gabriel.simon@etu.univ.fr',
    'tel' => 645123464,
    'adresse' => '9 Rue I',
    'genre' => 'Homme',
    'date_naissance' => '2005-09-05',
    'login' => 'gsimon',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  19 => 
  array (
    'prenom' => 'Lina',
    'nom' => 'Laurent',
    'mail' => 'lina.laurent@etu.univ.fr',
    'tel' => 645123465,
    'adresse' => '10 Rue J',
    'genre' => 'Femme',
    'date_naissance' => '2005-10-20',
    'login' => 'llaurent',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  20 => 
  array (
    'prenom' => 'Jules',
    'nom' => 'Lefebvre',
    'mail' => 'jules.lefebvre@etu.univ.fr',
    'tel' => 645123466,
    'adresse' => '11 Rue K',
    'genre' => 'Homme',
    'date_naissance' => '2005-11-15',
    'login' => 'jlefebvre',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  21 => 
  array (
    'prenom' => 'Lea',
    'nom' => 'Michel',
    'mail' => 'lea.michel@etu.univ.fr',
    'tel' => 645123467,
    'adresse' => '12 Rue L',
    'genre' => 'Femme',
    'date_naissance' => '2005-12-01',
    'login' => 'lmichel',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  22 => 
  array (
    'prenom' => 'Adam',
    'nom' => 'Garcia',
    'mail' => 'adam.garcia@etu.univ.fr',
    'tel' => 645123468,
    'adresse' => '13 Rue M',
    'genre' => 'Homme',
    'date_naissance' => '2006-01-10',
    'login' => 'agarcia',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  23 => 
  array (
    'prenom' => 'Manon',
    'nom' => 'David',
    'mail' => 'manon.david@etu.univ.fr',
    'tel' => 645123469,
    'adresse' => '14 Rue N',
    'genre' => 'Femme',
    'date_naissance' => '2006-02-14',
    'login' => 'mdavid',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  24 => 
  array (
    'prenom' => 'Arthur',
    'nom' => 'Bertrand',
    'mail' => 'arthur.bertrand@etu.univ.fr',
    'tel' => 645123470,
    'adresse' => '15 Rue O',
    'genre' => 'Homme',
    'date_naissance' => '2006-03-20',
    'login' => 'abertrand',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  25 => 
  array (
    'prenom' => 'Ines',
    'nom' => 'Roux',
    'mail' => 'ines.roux@etu.univ.fr',
    'tel' => 645123471,
    'adresse' => '16 Rue P',
    'genre' => 'Femme',
    'date_naissance' => '2006-04-25',
    'login' => 'iroux',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  26 => 
  array (
    'prenom' => 'Nathan',
    'nom' => 'Vincent',
    'mail' => 'nathan.vincent@etu.univ.fr',
    'tel' => 645123472,
    'adresse' => '17 Rue Q',
    'genre' => 'Homme',
    'date_naissance' => '2006-05-30',
    'login' => 'nvincent',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  27 => 
  array (
    'prenom' => 'Zoe',
    'nom' => 'Fournier',
    'mail' => 'zoe.fournier@etu.univ.fr',
    'tel' => 645123473,
    'adresse' => '18 Rue R',
    'genre' => 'Femme',
    'date_naissance' => '2006-06-05',
    'login' => 'zfournier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  28 => 
  array (
    'prenom' => 'Paul',
    'nom' => 'Morel',
    'mail' => 'paul.morel@etu.univ.fr',
    'tel' => 645123474,
    'adresse' => '19 Rue S',
    'genre' => 'Homme',
    'date_naissance' => '2006-07-10',
    'login' => 'pmorel',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  29 => 
  array (
    'prenom' => 'Camille',
    'nom' => 'Girard',
    'mail' => 'camille.girard@etu.univ.fr',
    'tel' => 645123475,
    'adresse' => '20 Rue T',
    'genre' => 'Femme',
    'date_naissance' => '2006-08-15',
    'login' => 'cgirard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  30 => 
  array (
    'prenom' => 'Theo',
    'nom' => 'Andre',
    'mail' => 'theo.andre@etu.univ.fr',
    'tel' => 645123476,
    'adresse' => '21 Rue U',
    'genre' => 'Homme',
    'date_naissance' => '2005-02-11',
    'login' => 'tandre',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  31 => 
  array (
    'prenom' => 'Lola',
    'nom' => 'Lefevre',
    'mail' => 'lola.lefevre@etu.univ.fr',
    'tel' => 645123477,
    'adresse' => '22 Rue V',
    'genre' => 'Femme',
    'date_naissance' => '2005-03-12',
    'login' => 'llefevre',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  32 => 
  array (
    'prenom' => 'Sacha',
    'nom' => 'Mercier',
    'mail' => 'sacha.mercier@etu.univ.fr',
    'tel' => 645123478,
    'adresse' => '23 Rue W',
    'genre' => 'Homme',
    'date_naissance' => '2005-04-13',
    'login' => 'smercier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  33 => 
  array (
    'prenom' => 'Eva',
    'nom' => 'Dupont',
    'mail' => 'eva.dupont@etu.univ.fr',
    'tel' => 645123479,
    'adresse' => '24 Rue X',
    'genre' => 'Femme',
    'date_naissance' => '2005-05-14',
    'login' => 'edupont',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  34 => 
  array (
    'prenom' => 'Tom',
    'nom' => 'Lambert',
    'mail' => 'tom.lambert@etu.univ.fr',
    'tel' => 645123480,
    'adresse' => '25 Rue Y',
    'genre' => 'Homme',
    'date_naissance' => '2005-06-15',
    'login' => 'tlambert',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  35 => 
  array (
    'prenom' => 'Agathe',
    'nom' => 'Bonnet',
    'mail' => 'agathe.bonnet@etu.univ.fr',
    'tel' => 645123481,
    'adresse' => '26 Rue Z',
    'genre' => 'Femme',
    'date_naissance' => '2005-07-16',
    'login' => 'abonnet',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  36 => 
  array (
    'prenom' => 'Gabin',
    'nom' => 'Francois',
    'mail' => 'gabin.francois@etu.univ.fr',
    'tel' => 645123482,
    'adresse' => '27 Rue AA',
    'genre' => 'Homme',
    'date_naissance' => '2005-08-17',
    'login' => 'gfrancois',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  37 => 
  array (
    'prenom' => 'Romane',
    'nom' => 'Martinez',
    'mail' => 'romane.martinez@etu.univ.fr',
    'tel' => 645123483,
    'adresse' => '28 Rue BB',
    'genre' => 'Femme',
    'date_naissance' => '2005-09-18',
    'login' => 'rmartinez',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  38 => 
  array (
    'prenom' => 'Mael',
    'nom' => 'Legrand',
    'mail' => 'mael.legrand@etu.univ.fr',
    'tel' => 645123484,
    'adresse' => '29 Rue CC',
    'genre' => 'Homme',
    'date_naissance' => '2005-10-19',
    'login' => 'mlegrand',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  39 => 
  array (
    'prenom' => 'Julia',
    'nom' => 'Garnier',
    'mail' => 'julia.garnier@etu.univ.fr',
    'tel' => 645123485,
    'adresse' => '30 Rue DD',
    'genre' => 'Femme',
    'date_naissance' => '2005-11-20',
    'login' => 'jgarnier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  40 => 
  array (
    'prenom' => 'Mathis',
    'nom' => 'Faure',
    'mail' => 'mathis.faure@etu.univ.fr',
    'tel' => 645123486,
    'adresse' => '31 Rue EE',
    'genre' => 'Homme',
    'date_naissance' => '2005-12-21',
    'login' => 'mfaure',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  41 => 
  array (
    'prenom' => 'Lou',
    'nom' => 'Rousseau',
    'mail' => 'lou.rousseau@etu.univ.fr',
    'tel' => 645123487,
    'adresse' => '32 Rue FF',
    'genre' => 'Femme',
    'date_naissance' => '2006-01-22',
    'login' => 'lrousseau',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  42 => 
  array (
    'prenom' => 'Evan',
    'nom' => 'Blanc',
    'mail' => 'evan.blanc@etu.univ.fr',
    'tel' => 645123488,
    'adresse' => '33 Rue GG',
    'genre' => 'Homme',
    'date_naissance' => '2006-02-23',
    'login' => 'eblanc',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  43 => 
  array (
    'prenom' => 'Sarah',
    'nom' => 'Guerin',
    'mail' => 'sarah.guerin@etu.univ.fr',
    'tel' => 645123489,
    'adresse' => '34 Rue HH',
    'genre' => 'Femme',
    'date_naissance' => '2006-03-24',
    'login' => 'sguerin',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  44 => 
  array (
    'prenom' => 'Enzo',
    'nom' => 'Muller',
    'mail' => 'enzo.muller@etu.univ.fr',
    'tel' => 645123490,
    'adresse' => '35 Rue II',
    'genre' => 'Homme',
    'date_naissance' => '2006-04-25',
    'login' => 'emuller',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  45 => 
  array (
    'prenom' => 'Charlotte',
    'nom' => 'Henry',
    'mail' => 'charlotte.henry@etu.univ.fr',
    'tel' => 645123491,
    'adresse' => '36 Rue JJ',
    'genre' => 'Femme',
    'date_naissance' => '2006-05-26',
    'login' => 'chenry',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  46 => 
  array (
    'prenom' => 'Valentin',
    'nom' => 'Roussel',
    'mail' => 'valentin.roussel@etu.univ.fr',
    'tel' => 645123492,
    'adresse' => '37 Rue KK',
    'genre' => 'Homme',
    'date_naissance' => '2006-06-27',
    'login' => 'vroussel',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  47 => 
  array (
    'prenom' => 'Juliette',
    'nom' => 'Nicolas',
    'mail' => 'juliette.nicolas@etu.univ.fr',
    'tel' => 645123493,
    'adresse' => '38 Rue LL',
    'genre' => 'Femme',
    'date_naissance' => '2006-07-28',
    'login' => 'jnicolas',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  48 => 
  array (
    'prenom' => 'Antoine',
    'nom' => 'Perrin',
    'mail' => 'antoine.perrin@etu.univ.fr',
    'tel' => 645123494,
    'adresse' => '39 Rue MM',
    'genre' => 'Homme',
    'date_naissance' => '2006-08-29',
    'login' => 'aperrin',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  49 => 
  array (
    'prenom' => 'Anna',
    'nom' => 'Morin',
    'mail' => 'anna.morin@etu.univ.fr',
    'tel' => 645123495,
    'adresse' => '40 Rue NN',
    'genre' => 'Femme',
    'date_naissance' => '2006-09-30',
    'login' => 'amorin',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  50 => 
  array (
    'prenom' => 'Axel',
    'nom' => 'Mathieu',
    'mail' => 'axel.mathieu@etu.univ.fr',
    'tel' => 645123496,
    'adresse' => '41 Rue OO',
    'genre' => 'Homme',
    'date_naissance' => '2005-01-11',
    'login' => 'amathieu',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  51 => 
  array (
    'prenom' => 'Alice',
    'nom' => 'Clement',
    'mail' => 'alice.clement@etu.univ.fr',
    'tel' => 645123497,
    'adresse' => '42 Rue PP',
    'genre' => 'Femme',
    'date_naissance' => '2005-02-12',
    'login' => 'aclement',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  52 => 
  array (
    'prenom' => 'Robin',
    'nom' => 'Gauthier',
    'mail' => 'robin.gauthier@etu.univ.fr',
    'tel' => 645123498,
    'adresse' => '43 Rue QQ',
    'genre' => 'Homme',
    'date_naissance' => '2005-03-13',
    'login' => 'rgauthier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  53 => 
  array (
    'prenom' => 'Margaux',
    'nom' => 'Dumont',
    'mail' => 'margaux.dumont@etu.univ.fr',
    'tel' => 645123499,
    'adresse' => '44 Rue RR',
    'genre' => 'Femme',
    'date_naissance' => '2005-04-14',
    'login' => 'mdumont',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  54 => 
  array (
    'prenom' => 'Maxime',
    'nom' => 'Lopez',
    'mail' => 'maxime.lopez@etu.univ.fr',
    'tel' => 645123500,
    'adresse' => '45 Rue SS',
    'genre' => 'Homme',
    'date_naissance' => '2005-05-15',
    'login' => 'mlopez',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  55 => 
  array (
    'prenom' => 'Lisa',
    'nom' => 'Fontaine',
    'mail' => 'lisa.fontaine@etu.univ.fr',
    'tel' => 645123501,
    'adresse' => '46 Rue TT',
    'genre' => 'Femme',
    'date_naissance' => '2005-06-16',
    'login' => 'lfontaine',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  56 => 
  array (
    'prenom' => 'Clement',
    'nom' => 'Chevalier',
    'mail' => 'clement.chevalier@etu.univ.fr',
    'tel' => 645123502,
    'adresse' => '47 Rue UU',
    'genre' => 'Homme',
    'date_naissance' => '2005-07-17',
    'login' => 'cchevalier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  57 => 
  array (
    'prenom' => 'Clara',
    'nom' => 'Robin',
    'mail' => 'clara.robin@etu.univ.fr',
    'tel' => 645123503,
    'adresse' => '48 Rue VV',
    'genre' => 'Femme',
    'date_naissance' => '2005-08-18',
    'login' => 'crobin',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  58 => 
  array (
    'prenom' => 'Baptiste',
    'nom' => 'Masson',
    'mail' => 'baptiste.masson@etu.univ.fr',
    'tel' => 645123504,
    'adresse' => '49 Rue WW',
    'genre' => 'Homme',
    'date_naissance' => '2005-09-19',
    'login' => 'bmasson',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  59 => 
  array (
    'prenom' => 'Ambre',
    'nom' => 'Sanchez',
    'mail' => 'ambre.sanchez@etu.univ.fr',
    'tel' => 645123505,
    'adresse' => '50 Rue XX',
    'genre' => 'Femme',
    'date_naissance' => '2005-10-20',
    'login' => 'asanchez',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  60 => 
  array (
    'prenom' => 'Corentin',
    'nom' => 'Gerard',
    'mail' => 'corentin.gerard@etu.univ.fr',
    'tel' => 645123506,
    'adresse' => '51 Rue YY',
    'genre' => 'Homme',
    'date_naissance' => '2005-11-21',
    'login' => 'cgerard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  61 => 
  array (
    'prenom' => 'Juliette',
    'nom' => 'Nguyen',
    'mail' => 'juliette.nguyen@etu.univ.fr',
    'tel' => 645123507,
    'adresse' => '52 Rue ZZ',
    'genre' => 'Femme',
    'date_naissance' => '2005-12-22',
    'login' => 'jnguyen',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  62 => 
  array (
    'prenom' => 'Zoe',
    'nom' => 'Boyer',
    'mail' => 'zoe.boyer@etu.univ.fr',
    'tel' => 645123508,
    'adresse' => '53 Rue AAA',
    'genre' => 'Femme',
    'date_naissance' => '2006-01-23',
    'login' => 'zboyer',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  63 => 
  array (
    'prenom' => 'Louise',
    'nom' => 'Denis',
    'mail' => 'louise.denis@etu.univ.fr',
    'tel' => 645123509,
    'adresse' => '54 Rue BBB',
    'genre' => 'Femme',
    'date_naissance' => '2006-02-24',
    'login' => 'ldenis',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  64 => 
  array (
    'prenom' => 'Mia',
    'nom' => 'Lemaire',
    'mail' => 'mia.lemaire@etu.univ.fr',
    'tel' => 645123510,
    'adresse' => '55 Rue CCC',
    'genre' => 'Femme',
    'date_naissance' => '2006-03-25',
    'login' => 'mlemaire',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  65 => 
  array (
    'prenom' => 'Lina',
    'nom' => 'Duval',
    'mail' => 'lina.duval@etu.univ.fr',
    'tel' => 645123511,
    'adresse' => '56 Rue DDD',
    'genre' => 'Femme',
    'date_naissance' => '2006-04-26',
    'login' => 'lduval',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  66 => 
  array (
    'prenom' => 'Eva',
    'nom' => 'Joly',
    'mail' => 'eva.joly@etu.univ.fr',
    'tel' => 645123512,
    'adresse' => '57 Rue EEE',
    'genre' => 'Femme',
    'date_naissance' => '2006-05-27',
    'login' => 'ejoly',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  67 => 
  array (
    'prenom' => 'Charlotte',
    'nom' => 'Gautier',
    'mail' => 'charlotte.gautier@etu.univ.fr',
    'tel' => 645123513,
    'adresse' => '58 Rue FFF',
    'genre' => 'Femme',
    'date_naissance' => '2006-06-28',
    'login' => 'cgautier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  68 => 
  array (
    'prenom' => 'Ambre',
    'nom' => 'Roger',
    'mail' => 'ambre.roger@etu.univ.fr',
    'tel' => 645123514,
    'adresse' => '59 Rue GGG',
    'genre' => 'Femme',
    'date_naissance' => '2006-07-29',
    'login' => 'aroger',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  69 => 
  array (
    'prenom' => 'Rose',
    'nom' => 'Roche',
    'mail' => 'rose.roche@etu.univ.fr',
    'tel' => 645123515,
    'adresse' => '60 Rue HHH',
    'genre' => 'Femme',
    'date_naissance' => '2006-08-30',
    'login' => 'rroche',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  70 => 
  array (
    'prenom' => 'Mila',
    'nom' => 'Roy',
    'mail' => 'mila.roy@etu.univ.fr',
    'tel' => 645123516,
    'adresse' => '61 Rue III',
    'genre' => 'Femme',
    'date_naissance' => '2005-09-01',
    'login' => 'mroy',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  71 => 
  array (
    'prenom' => 'Pierre',
    'nom' => 'Noel',
    'mail' => 'pierre.noel@etu.univ.fr',
    'tel' => 645123517,
    'adresse' => '62 Rue JJJ',
    'genre' => 'Homme',
    'date_naissance' => '2005-10-02',
    'login' => 'pnoel',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  72 => 
  array (
    'prenom' => 'Timothe',
    'nom' => 'Meyer',
    'mail' => 'timothe.meyer@etu.univ.fr',
    'tel' => 645123518,
    'adresse' => '63 Rue KKK',
    'genre' => 'Homme',
    'date_naissance' => '2005-11-03',
    'login' => 'tmeyer',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  73 => 
  array (
    'prenom' => 'Nolan',
    'nom' => 'Lucas',
    'mail' => 'nolan.lucas@etu.univ.fr',
    'tel' => 645123519,
    'adresse' => '64 Rue LLL',
    'genre' => 'Homme',
    'date_naissance' => '2005-12-04',
    'login' => 'nlucas',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  74 => 
  array (
    'prenom' => 'Lenny',
    'nom' => 'Meunier',
    'mail' => 'lenny.meunier@etu.univ.fr',
    'tel' => 645123520,
    'adresse' => '65 Rue MMM',
    'genre' => 'Homme',
    'date_naissance' => '2006-01-05',
    'login' => 'lmeunier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  75 => 
  array (
    'prenom' => 'Mohamed',
    'nom' => 'Jean',
    'mail' => 'mohamed.jean@etu.univ.fr',
    'tel' => 645123521,
    'adresse' => '66 Rue NNN',
    'genre' => 'Homme',
    'date_naissance' => '2006-02-06',
    'login' => 'mjean',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  76 => 
  array (
    'prenom' => 'Yanis',
    'nom' => 'Perez',
    'mail' => 'yanis.perez@etu.univ.fr',
    'tel' => 645123522,
    'adresse' => '67 Rue OOO',
    'genre' => 'Homme',
    'date_naissance' => '2006-03-07',
    'login' => 'yperez',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  77 => 
  array (
    'prenom' => 'Adrien',
    'nom' => 'Marchand',
    'mail' => 'adrien.marchand@etu.univ.fr',
    'tel' => 645123523,
    'adresse' => '68 Rue PPP',
    'genre' => 'Homme',
    'date_naissance' => '2006-04-08',
    'login' => 'amarchand',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  78 => 
  array (
    'prenom' => 'Kylian',
    'nom' => 'Dufour',
    'mail' => 'kylian.dufour@etu.univ.fr',
    'tel' => 645123524,
    'adresse' => '69 Rue QQQ',
    'genre' => 'Homme',
    'date_naissance' => '2006-05-09',
    'login' => 'kdufour',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  79 => 
  array (
    'prenom' => 'Bastien',
    'nom' => 'Blanchard',
    'mail' => 'bastien.blanchard@etu.univ.fr',
    'tel' => 645123525,
    'adresse' => '70 Rue RRR',
    'genre' => 'Homme',
    'date_naissance' => '2006-06-10',
    'login' => 'bblanchard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  80 => 
  array (
    'prenom' => 'Damien',
    'nom' => 'Marie',
    'mail' => 'damien.marie@etu.univ.fr',
    'tel' => 645123526,
    'adresse' => '71 Rue SSS',
    'genre' => 'Homme',
    'date_naissance' => '2005-07-11',
    'login' => 'dmarie',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  81 => 
  array (
    'prenom' => 'Dorian',
    'nom' => 'Barbier',
    'mail' => 'dorian.barbier@etu.univ.fr',
    'tel' => 645123527,
    'adresse' => '72 Rue TTT',
    'genre' => 'Homme',
    'date_naissance' => '2005-08-12',
    'login' => 'dbarbier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  82 => 
  array (
    'prenom' => 'Benjamin',
    'nom' => 'Brun',
    'mail' => 'benjamin.brun@etu.univ.fr',
    'tel' => 645123528,
    'adresse' => '73 Rue UUU',
    'genre' => 'Homme',
    'date_naissance' => '2005-09-13',
    'login' => 'bbrun',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  83 => 
  array (
    'prenom' => 'Florian',
    'nom' => 'Dumas',
    'mail' => 'florian.dumas@etu.univ.fr',
    'tel' => 645123529,
    'adresse' => '74 Rue VVV',
    'genre' => 'Homme',
    'date_naissance' => '2005-10-14',
    'login' => 'fdumas',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  84 => 
  array (
    'prenom' => 'Jeremy',
    'nom' => 'Brunet',
    'mail' => 'jeremy.brunet@etu.univ.fr',
    'tel' => 645123530,
    'adresse' => '75 Rue WWW',
    'genre' => 'Homme',
    'date_naissance' => '2005-11-15',
    'login' => 'jbrunet',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  85 => 
  array (
    'prenom' => 'Matthieu',
    'nom' => 'Leroux',
    'mail' => 'matthieu.leroux@etu.univ.fr',
    'tel' => 645123531,
    'adresse' => '76 Rue XXX',
    'genre' => 'Homme',
    'date_naissance' => '2005-12-16',
    'login' => 'mleroux',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  86 => 
  array (
    'prenom' => 'Nicolas',
    'nom' => 'Koné',
    'mail' => 'nicolas.kone@etu.univ.fr',
    'tel' => 645123532,
    'adresse' => '77 Rue YYY',
    'genre' => 'Homme',
    'date_naissance' => '2006-01-17',
    'login' => 'nkone',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  87 => 
  array (
    'prenom' => 'Quentin',
    'nom' => 'Renard',
    'mail' => 'quentin.renard@etu.univ.fr',
    'tel' => 645123533,
    'adresse' => '78 Rue ZZZ',
    'genre' => 'Homme',
    'date_naissance' => '2006-02-18',
    'login' => 'qrenard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  88 => 
  array (
    'prenom' => 'Samuel',
    'nom' => 'Vidal',
    'mail' => 'samuel.vidal@etu.univ.fr',
    'tel' => 645123534,
    'adresse' => '79 Rue AAAA',
    'genre' => 'Homme',
    'date_naissance' => '2006-03-19',
    'login' => 'svidal',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  89 => 
  array (
    'prenom' => 'Simon',
    'nom' => 'Leclerc',
    'mail' => 'simon.leclerc@etu.univ.fr',
    'tel' => 645123535,
    'adresse' => '80 Rue BBBB',
    'genre' => 'Homme',
    'date_naissance' => '2006-04-20',
    'login' => 'sleclerc',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  90 => 
  array (
    'prenom' => 'Tristan',
    'nom' => 'Schmitt',
    'mail' => 'tristan.schmitt@etu.univ.fr',
    'tel' => 645123536,
    'adresse' => '81 Rue CCCC',
    'genre' => 'Homme',
    'date_naissance' => '2005-05-21',
    'login' => 'tschmitt',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  91 => 
  array (
    'prenom' => 'Victor',
    'nom' => 'Picard',
    'mail' => 'victor.picard@etu.univ.fr',
    'tel' => 645123537,
    'adresse' => '82 Rue DDDD',
    'genre' => 'Homme',
    'date_naissance' => '2005-06-22',
    'login' => 'vpicard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  92 => 
  array (
    'prenom' => 'Vincent',
    'nom' => 'Caron',
    'mail' => 'vincent.caron@etu.univ.fr',
    'tel' => 645123538,
    'adresse' => '83 Rue EEEE',
    'genre' => 'Homme',
    'date_naissance' => '2005-07-23',
    'login' => 'vcaron',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  93 => 
  array (
    'prenom' => 'Xavier',
    'nom' => 'Colin',
    'mail' => 'xavier.colin@etu.univ.fr',
    'tel' => 645123539,
    'adresse' => '84 Rue FFFF',
    'genre' => 'Homme',
    'date_naissance' => '2005-08-24',
    'login' => 'xcolin',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  94 => 
  array (
    'prenom' => 'Yoann',
    'nom' => 'Maillard',
    'mail' => 'yoann.maillard@etu.univ.fr',
    'tel' => 645123540,
    'adresse' => '85 Rue GGGG',
    'genre' => 'Homme',
    'date_naissance' => '2005-09-25',
    'login' => 'ymaillard',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  95 => 
  array (
    'prenom' => 'Audrey',
    'nom' => 'Riviere',
    'mail' => 'audrey.riviere@etu.univ.fr',
    'tel' => 645123541,
    'adresse' => '86 Rue HHHH',
    'genre' => 'Femme',
    'date_naissance' => '2005-10-26',
    'login' => 'ariviere',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  96 => 
  array (
    'prenom' => 'Claire',
    'nom' => 'Aubert',
    'mail' => 'claire.aubert@etu.univ.fr',
    'tel' => 645123542,
    'adresse' => '87 Rue IIII',
    'genre' => 'Femme',
    'date_naissance' => '2005-11-27',
    'login' => 'caubert',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  97 => 
  array (
    'prenom' => 'Elodie',
    'nom' => 'Giraud',
    'mail' => 'elodie.giraud@etu.univ.fr',
    'tel' => 645123543,
    'adresse' => '88 Rue JJJJ',
    'genre' => 'Femme',
    'date_naissance' => '2005-12-28',
    'login' => 'egiraud',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  98 => 
  array (
    'prenom' => 'Fanny',
    'nom' => 'Leveque',
    'mail' => 'fanny.leveque@etu.univ.fr',
    'tel' => 645123544,
    'adresse' => '89 Rue KKKK',
    'genre' => 'Femme',
    'date_naissance' => '2006-01-29',
    'login' => 'fleveque',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  99 => 
  array (
    'prenom' => 'Helene',
    'nom' => 'Lemoine',
    'mail' => 'helene.lemoine@etu.univ.fr',
    'tel' => 645123545,
    'adresse' => '90 Rue LLLL',
    'genre' => 'Femme',
    'date_naissance' => '2006-02-28',
    'login' => 'hlemoine',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  100 => 
  array (
    'prenom' => 'Julie',
    'nom' => 'Pasquier',
    'mail' => 'julie.pasquier@etu.univ.fr',
    'tel' => 645123546,
    'adresse' => '91 Rue MMMM',
    'genre' => 'Femme',
    'date_naissance' => '2006-03-01',
    'login' => 'jpasquier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  101 => 
  array (
    'prenom' => 'Laura',
    'nom' => 'Guillot',
    'mail' => 'laura.guillot@etu.univ.fr',
    'tel' => 645123547,
    'adresse' => '92 Rue NNNN',
    'genre' => 'Femme',
    'date_naissance' => '2006-04-02',
    'login' => 'lguillot',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  102 => 
  array (
    'prenom' => 'Lucie',
    'nom' => 'Lecomte',
    'mail' => 'lucie.lecomte@etu.univ.fr',
    'tel' => 645123548,
    'adresse' => '93 Rue OOOO',
    'genre' => 'Femme',
    'date_naissance' => '2006-05-03',
    'login' => 'llecomte',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  103 => 
  array (
    'prenom' => 'Marion',
    'nom' => 'Guyot',
    'mail' => 'marion.guyot@etu.univ.fr',
    'tel' => 645123549,
    'adresse' => '94 Rue PPPP',
    'genre' => 'Femme',
    'date_naissance' => '2006-06-04',
    'login' => 'mguyot',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  104 => 
  array (
    'prenom' => 'Melanie',
    'nom' => 'Renaud',
    'mail' => 'melanie.renaud@etu.univ.fr',
    'tel' => 645123550,
    'adresse' => '95 Rue QQQQ',
    'genre' => 'Femme',
    'date_naissance' => '2006-07-05',
    'login' => 'mrenaud',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  105 => 
  array (
    'prenom' => 'Morgane',
    'nom' => 'Carpentier',
    'mail' => 'morgane.carpentier@etu.univ.fr',
    'tel' => 645123551,
    'adresse' => '96 Rue RRRR',
    'genre' => 'Femme',
    'date_naissance' => '2006-08-06',
    'login' => 'mcarpentier',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  106 => 
  array (
    'prenom' => 'Oceane',
    'nom' => 'Huet',
    'mail' => 'oceane.huet@etu.univ.fr',
    'tel' => 645123552,
    'adresse' => '97 Rue SSSS',
    'genre' => 'Femme',
    'date_naissance' => '2006-09-07',
    'login' => 'ohuet',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  107 => 
  array (
    'prenom' => 'Pauline',
    'nom' => 'Masse',
    'mail' => 'pauline.masse@etu.univ.fr',
    'tel' => 645123553,
    'adresse' => '98 Rue TTTT',
    'genre' => 'Femme',
    'date_naissance' => '2006-10-08',
    'login' => 'pmasse',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  108 => 
  array (
    'prenom' => 'Raphaelle',
    'nom' => 'Hamon',
    'mail' => 'raphaelle.hamon@etu.univ.fr',
    'tel' => 645123554,
    'adresse' => '99 Rue UUUU',
    'genre' => 'Femme',
    'date_naissance' => '2006-11-09',
    'login' => 'rhamon',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
  109 => 
  array (
    'prenom' => 'Solene',
    'nom' => 'Bailly',
    'mail' => 'solene.bailly@etu.univ.fr',
    'tel' => 645123555,
    'adresse' => '100 Rue VVVV',
    'genre' => 'Femme',
    'date_naissance' => '2006-12-10',
    'login' => 'sbailly',
    'motdepasse' => 'etu123',
    'statut' => 'ETUDIANT',
  ),
);
